config/routes.rb
Rails.application.routes.draw do
  get 'friend/add_friend'

  get 'sessions/new'

  get 'users/new'

  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get   '/search',  to:   'users#search'
  get '/add_friend', to: 'friend#add_friend'
  get '/confirm',  to:  'friend#confirm'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'static_pages#home'
resources :users

resources :users do
    get :search, :on => :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	before_save { email.downcase! }
	validates :name, presence: true, length: { maximum: 50 }
	validates :username, presence: true, length: { maximum: 50 },
							uniqueness: true
	
	 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
							format: { with: VALID_EMAIL_REGEX },
							uniqueness: {case_sensitive: false}

	has_secure_password
	VALID_PASSWORD_REGEX = /\A(?=.*\d)(?=.*([a-z]|[A-Z]))([\x20-\x7E]){8,20}\z/
	validates :password, presence: true, 	
	 						length: { minimum: 8 },
							format: { with: VALID_PASSWORD_REGEX }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.search(term)
    User.where('name LIKE ? OR username LIKE ?', "%#{term}%", "%#{term}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def hello
  	render html: "Hello World"
  end
end

app/controllers/friend_controller.rb
class FriendController < ApplicationController
  
  def add_friend
  	fri = Friend.find(params[:id])
  	fri.status = 1
  	first = fri.f2_username
  	second = fri.f1_username

  	if fri.save 
  		frit = Friend.where('f1_username LIKE ? AND f2_username LIKE ?', "%#{first}%", "%#{second}%").update_all(status: 2)
    	redirect_to current_user
    end
  end

  def confirm
  	if Friend.where('f1_username LIKE ? OR f2_username LIKE ?', "%#{params[:f1]}%", "%#{params[:f2]}%").limit(1).update_all(status: 3)
  	   flash[:success] = "Friend list updated"
    else
        flash[:danger] = "Some error occurs in making your Friend"
    end
    # fri.status = 3
  	first = params[:f2]
  	second = params[:f1]

  	# if fri.save 
  	if Friend.where('f1_username LIKE ? OR f2_username LIKE ?', "%#{first}%", "%#{second}%").limit(1).update_all(status: 3)
       flash[:success] = "Friend list updated"
    else
        flash[:danger] = "Some error occurs in making your Friend"
    end
    redirect_to current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
  	 log_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	 @user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

   def create
    @user = User.new(user_params)    
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Brisk-le"
      redirect_to @user
    else
      render 'new'
    end
  end

   def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :username, :used)
    end

    def index
      @users = User.order(:username).limit(50)
    end

    def search
      respond_to do |format|
        format.html
        format.json { @users = User.search(params[:term]) }
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friend_helper.rb
module FriendHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	# Logs in the given user.
	def log_in(user)
		session[:user_id] = user.id
	end

	# Returns the current logged-in user (if any).
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	# Returns true if the user is logged in, false otherwise.
	def logged_in?
		!current_user.nil?
	end

	# Logs out the current user.
	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friend/add_friend.html.erb
<h1>Friend#add_friend</h1>
<p>Find me in app/views/friend/add_friend.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="#">Brisk-le</a>
    by <a href="#">Shaique</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "B R I S K - le", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <title><%= yield(:title) %> | Brisk-le</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= render 'layouts/shim' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "B R I S K - le", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Help",   help_path %></li>
             <% if logged_in? %>
          		<li><%= link_to "Users", '#' %></li>
            	 <li class="dropdown">
		            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
		              Account <b class="caret"></b>
		            </a>
		            <ul class="dropdown-menu">
		              <li><%= link_to "Profile", current_user %></li>
		              <li><%= link_to "Settings", '#' %></li>
		              <li class="divider"></li>
		              <li>
		                <%= link_to "Log out", logout_path, method: :delete %>
		              </li>
		            </ul>
	          </li>
	          <% else %>
            	<li><%= link_to "Log in", login_path %></li>
            	<% end %>
          </ul>
        </nav>
      </div>
    </header>
    
        <script>
        $(function() {
          <%= yield :script %>
        });
      </script>

      
    <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
     <!-- <%= debug(params) if Rails.env.development? %> -->
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Brisk-le</title>
  </head>
  <body>
    <h1>About</h1>
    <p>
      The Brisk-le is a social network which will ease your gathering.
      This is just a sample application for the Brisk-le.
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Please help us to improve.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
  <head>
     <title><%= yield(:title) %> | Brisk-le</title>
  </head>
  <body>
    <h1>Help</h1>
    <p>
      Under construction :-)
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Brisk-le</title>
  </head>
  <body>
   <div class="center jumbotron">
  <h1>Welcome to the Brisk-le</h1>

  <h2>
    This is the home page of your Brisk-le Circle.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

  </body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>

      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.hidden_field :used, :value =>0, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/search.html.erb
<h1>Users</h1>
<%= link_to 'New User', signup_path %>

<div class="users-search">
	<input type="text" id="users-search-txt" autofocus>
	<div id="users-search-results"> </div>
</div>


<%= content_for :script do %>
new app.User;
<% end %>

app/views/users/show.html.erb
<h3><%= link_to "Search Users",   search_path %></h3>

<h1> List of all other people at Brisk-le </h1>
<table>
	<tr>
		<th>Name</th>
		<th>Username</th>
		<th>Email</th>
	</tr>
	<% @user_details = User.all %>
	<% @user_details.each do |data| %>
	<% if data.username != @user.username %>	
		<tr>
			<td><%= data.name %></td>
			<td><%= data.username %></td>
			<td><%= data.email %></td>
		</tr>
		<% end %>
	<% end %>
</table>

<!-- 
<%= @user.name %>, <%= @user.email %>, <%= @user.username %> 
-->

	<% usernames = Array.new %>
	<% @fri = Friend.where(f1_username: @user.username)   %>
	<% @fri.each do |friend| %>
	<% usernames.insert(-1, friend.f2_username) %>
	<% end %>
	

<% @user_details = User.all %>
<% @user_details.each do |data| %>
<% if data.username != @user.username %>	
	<% if usernames.include?(data.username) %>
	<% %>
	<% else %>
	<% friI = Friend.new(f1_username: @user.username, f2_username: data.username, 	
														status: 0)  %>
		    <% if friI.save %>
		    <% %>  
		    <% else %>
		    <%	flash[:danger] = "Some error occurs while updating Friend" %>
		    <%  	render 'new'	%>
		    <% end %>
	<% friI = Friend.new(f1_username: data.username, f2_username: @user.username, 	
														status: 0)   
														%>
		    <% if friI.save %>
		   	<% %>  
		    <% else %>
		    <%	flash[:danger] = "Some error occurs while updating Friend" %>
		    <%  	render 'new'	%>
		    <% end %>
			    
	<% end %>	  	  
<% end %>
<% end %>	


		


<h3> Connect with the people </h3>

<table>
	<tr>
		<th>Username 1</th>
		<th>Username 2</th>
		<th> Status </th>
	</tr>
	<% @fri = Friend.where(:f1_username => @user.username) %>
	<% @fri.each do |data| %>
		<tr>
			<td><%= data.f1_username %></td>
			<td><%= data.f2_username %></td>
			<% if data.status == 0 %>
				<td> <%= link_to "Add friend", add_friend_path(:id => data.id) %> </td>
			<% elsif data.status == 1 %>
				<td> Friend Request Sent </td>
			<% elsif data.status == 2 %>
				<td> <%= link_to "Confirm friend",   confirm_path(:f1 => data.f1_username, :f2 => data.f2_username) %> </td>
			<% else %>
				<td> Friends </td>
			<% end %>
		</tr>
		
	<% end %>
</table>


<!-- <h3> See the friends status </h3>

<table>
	<tr>
		<th>Username 1</th>
		<th>Username 2</th>
		<th> Status </th>
	</tr>
	<% @fri = Friend.where(:f1_username => @user.username) %>
	<% @fri.each do |data| %>
		<tr>
			<td><%= data.f1_username %></td>
			<td><%= data.f2_username %></td>
			<td><%= data.status  %></td>
	<% end %>
		</tr>
		
</table>
 -->